#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const input = process.argv[2] || "css/legacy.css";
const output = process.argv[3] || "styles.css";

const sourcePath = path.resolve(root, input);
const outputPath = path.resolve(root, output);
const css = fs.readFileSync(sourcePath, "utf8");

const contentFiles = [
  "index.html",
  "app.js",
  "employee-data.js",
  "js/auth.js",
  "js/helpers.js",
  "js/icons.js",
  "js/showcase.js",
  ...fs.readdirSync(path.resolve(root, "js/pages"))
    .filter((file) => file.endsWith(".js"))
    .map((file) => `js/pages/${file}`),
].filter((file) => fs.existsSync(path.resolve(root, file)));

const content = contentFiles
  .map((file) => fs.readFileSync(path.resolve(root, file), "utf8"))
  .join("\n");

const tokens = new Set();
for (const match of content.matchAll(/[A-Za-z_][A-Za-z0-9_-]{1,}/g)) {
  tokens.add(match[0]);
}

[
  "open",
  "mobile-open",
  "is-active",
  "is-visible",
  "is-open",
  "active",
  "scrolled",
  "page-entering",
  "page-exiting",
  "admin-mode",
  "dir-unlocked",
  "wn-sel-active",
  "hidden",
  "show",
  "toast-show",
  "toast-hide",
  "anim-up",
  "anim-left",
  "anim-right",
  "anim-scale",
  "fade-up",
  "fdb-reveal",
  "fdb-visible",
  "show-real-card-tiktok",
  "show-real-card-facebook",
  "show-real-card-medium",
  "show-real-platform-icon",
  "slc-platform-corner-icon",
  "show-real-card-track-bd",
  "show-real-card-track-design",
  "show-real-card-track-dev",
  "show-real-card-track-mk",
].forEach((token) => tokens.add(token));

const keepKeyframes = new Set();
for (const match of css.matchAll(/animation(?:-name)?\s*:\s*([^;{}]+)/g)) {
  for (const part of match[1].split(",")) {
    const name = part.trim().split(/\s+/)[0];
    if (
      /^[A-Za-z_-]/.test(name) &&
      !["none", "linear", "ease", "ease-in", "ease-out", "ease-in-out", "var"].includes(name)
    ) {
      keepKeyframes.add(name);
    }
  }
}

function findBlockEnd(index) {
  let depth = 1;
  let quote = null;
  let escaped = false;
  let parenDepth = 0;

  for (let i = index; i < css.length; i += 1) {
    const char = css[i];
    if (quote) {
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === quote) quote = null;
      continue;
    }

    if (char === "\"" || char === "'") {
      quote = char;
      continue;
    }
    if (char === "(") {
      parenDepth += 1;
      continue;
    }
    if (char === ")") {
      parenDepth = Math.max(0, parenDepth - 1);
      continue;
    }
    if (parenDepth) continue;

    if (char === "{") depth += 1;
    else if (char === "}" && --depth === 0) return i;
  }

  return css.length - 1;
}

function stripComments(value) {
  return value.replace(/\/\*[\s\S]*?\*\//g, "");
}

function selectorUsed(selector) {
  const cleanedSelector = stripComments(selector).trim();
  if (!cleanedSelector) return false;

  if (
    cleanedSelector.startsWith(":root") ||
    /^(html|body|\*|img|a|button|h1|h2|h3|h4|p|code|ul|li|svg|section|article)(\b|[:.#\[])/.test(cleanedSelector)
  ) {
    return true;
  }

  return cleanedSelector.split(",").some((part) => {
    const cleanPart = part.replace(
      /:(hover|focus|focus-visible|focus-within|active|visited|disabled|checked|before|after|first-child|last-child|nth-child\([^)]*\)|not\([^)]*\)|has\([^)]*\)|is\([^)]*\)|where\([^)]*\))/g,
      " ",
    );
    const classes = [...cleanPart.matchAll(/\.([A-Za-z_-][A-Za-z0-9_-]*)/g)].map((match) => match[1]);
    const ids = [...cleanPart.matchAll(/#([A-Za-z_-][A-Za-z0-9_-]*)/g)].map((match) => match[1]);

    if (!classes.length && !ids.length) return true;
    return classes.every((name) => tokens.has(name)) && ids.every((name) => tokens.has(name));
  });
}

function purgeRange(start, end) {
  let outputCss = "";
  let index = start;

  while (index < end) {
    const openIndex = css.indexOf("{", index);
    if (openIndex < 0 || openIndex >= end) break;

    const prelude = css.slice(index, openIndex).trim();
    const closeIndex = findBlockEnd(openIndex + 1);
    const fullRule = css.slice(index, closeIndex + 1);

    if (prelude.startsWith("@")) {
      const atName = prelude.split(/\s+/)[0];

      if (["@font-face", "@property"].includes(atName)) {
        outputCss += `${fullRule}\n`;
      } else if (["@keyframes", "@-webkit-keyframes"].includes(atName)) {
        const name = prelude.split(/\s+/)[1];
        if (keepKeyframes.has(name)) outputCss += `${fullRule}\n`;
      } else if (["@media", "@supports", "@layer", "@container"].includes(atName)) {
        const inner = purgeRange(openIndex + 1, closeIndex);
        if (inner.trim()) outputCss += `${prelude}{\n${inner}}\n`;
      } else {
        outputCss += `${fullRule}\n`;
      }
    } else if (!prelude.startsWith(":root") && selectorUsed(prelude)) {
      outputCss += `${fullRule}\n`;
    }

    index = closeIndex + 1;
  }

  return outputCss;
}

const header = `/* Generated by scripts/purge-css.mjs from ${input}. Edit css/design-system.css for tokens. */\n@import "./css/design-system.css";\n`;
const purged = `${header}${purgeRange(0, css.length)}`;
fs.writeFileSync(outputPath, purged);

const originalBytes = Buffer.byteLength(css);
const outputBytes = Buffer.byteLength(purged);
const pct = Math.round((outputBytes / originalBytes) * 100);

console.log(`CSS purge: ${input} ${originalBytes} bytes -> ${output} ${outputBytes} bytes (${pct}%)`);
